env:
  browser: true
  es6: true
  jquery: true
  mocha: true
extends: airbnb
parserOptions:
  sourceType: module
globals:
  axios: true
  KeyframeTweener: true
  SampleSpriteLibrary: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
